[tool.pyright]
include = ["tests", "effectful"]
exclude = ["**/node_modules",
    "**/__pycache__",
    "effectful.egg-info"
]
pythonVersion = "3.12"
reportMissingImports = true
reportAttributeAccessIssue = false
reportCallIssue = false
reportGeneralTypeIssues = false
reportMissingModuleSource = false
reportOperatorIssue = false
reportInvalidTypeForm = false
reportIncompatibleVariableOverride = false
reportArgumentType = false
reportIndexIssue = false
reportPossiblyUnboundVariable = false
reportReturnType = false
