name: Lint

on:
  push:
    branches: [master]
  pull_request:
    branches: 
      - master
      - 'staging-*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10']
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: setup.py

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.3"

      - name: Install dependencies
        run: |
          uv pip install .[dev]

      - name: Lint
        run: ./scripts/lint.sh
