name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: 
      - master
      - 'staging-*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["'<3.13'", "'>=3.13'"]
    steps:
      - uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install Python dependencies
        run: |
          uv sync --docs --python ${{ matrix.python-version }}
          
      - name: Build docs
        run: cd docs && uv run make html
