name: Build Docs

on:
  push:
    branches: [master]
  pull_request:
    branches: 
      - master
      - 'staging-*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install Python dependencies
        run: |
          uv sync --all-extras --dev
          
      - name: Build docs
        run: |
          cd docs && uv run make html
